
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xb8\xc8\x00\xd1\xf7\x17:\xd3\xb6\x05\x06\xe5s\x11\xabR'
    
_lr_action_items = {'TAGCLOSEOPEN':([2,4,5,11,12,17,18,19,21,22,27,],[-2,-1,-18,16,-16,-3,-17,-15,-6,-4,-5,]),'TAGCLOSE':([6,7,8,9,10,14,15,23,24,28,31,32,],[-10,-9,-7,-18,-8,-12,22,27,-18,-11,-13,-14,]),'ATTRVALOPEN':([20,],[25,]),'BUTTON':([1,16,],[6,6,]),'OBJECT':([1,16,],[7,7,]),'SCENE':([1,16,],[8,8,]),'MANIFEST':([1,16,],[10,10,]),'ATTRVALSTR':([25,],[29,]),'ATTRVALCLOSE1':([30,],[32,]),'TAGLONE':([6,7,8,9,10,14,15,24,28,31,32,],[-10,-9,-7,-18,-8,-12,21,-18,-11,-13,-14,]),'ATTRVALSTR1':([26,],[30,]),'ATTRS':([6,7,8,9,10,24,31,32,],[-10,-9,-7,13,-8,13,-13,-14,]),'ATTRVALCLOSE':([29,],[31,]),'ATTRVALOPEN1':([20,],[26,]),'ATTRASSIGN':([13,],[20,]),'TAGOPEN':([0,2,4,5,11,12,17,18,19,21,22,27,],[1,-2,-1,-18,1,-16,-3,-17,-15,-6,-4,-5,]),'$end':([2,3,4,17,21,27,],[-2,0,-1,-3,-6,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'atributo':([20,],[24,]),'closetag':([11,],[17,]),'lonetag':([0,11,],[2,2,]),'tag':([0,11,],[3,18,]),'attrs':([9,24,],[15,28,]),'tagname':([1,16,],[9,23,]),'child':([5,],[11,]),'simpletag':([0,11,],[4,4,]),'opentag':([0,11,],[5,5,]),'children':([11,],[19,]),'lambda':([5,9,24,],[12,14,14,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> tag","S'",1,None,None,None),
  ('tag -> simpletag','tag',1,'p_tag','jera.py',103),
  ('tag -> lonetag','tag',1,'p_tag','jera.py',104),
  ('simpletag -> opentag child closetag','simpletag',3,'p_simpletag','jera.py',109),
  ('opentag -> TAGOPEN tagname attrs TAGCLOSE','opentag',4,'p_opentag','jera.py',117),
  ('closetag -> TAGCLOSEOPEN tagname TAGCLOSE','closetag',3,'p_closetag','jera.py',128),
  ('lonetag -> TAGOPEN tagname attrs TAGLONE','lonetag',4,'p_lonetag','jera.py',132),
  ('tagname -> SCENE','tagname',1,'p_tagname','jera.py',144),
  ('tagname -> MANIFEST','tagname',1,'p_tagname','jera.py',145),
  ('tagname -> OBJECT','tagname',1,'p_tagname','jera.py',146),
  ('tagname -> BUTTON','tagname',1,'p_tagname','jera.py',147),
  ('attrs -> ATTRS ATTRASSIGN atributo attrs','attrs',4,'p_attrs','jera.py',151),
  ('attrs -> lambda','attrs',1,'p_attrs','jera.py',152),
  ('atributo -> ATTRVALOPEN ATTRVALSTR ATTRVALCLOSE','atributo',3,'p_atributo','jera.py',161),
  ('atributo -> ATTRVALOPEN1 ATTRVALSTR1 ATTRVALCLOSE1','atributo',3,'p_atributo','jera.py',162),
  ('child -> child children','child',2,'p_child','jera.py',168),
  ('child -> lambda','child',1,'p_child','jera.py',169),
  ('children -> tag','children',1,'p_children','jera.py',180),
  ('lambda -> <empty>','lambda',0,'p_lambda','jera.py',184),
]
