
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xffZ\x92#\xeb\x9f\x06m~\x83K\x02\xf7\xd5\x1fH'
    
_lr_action_items = {'TAGCLOSEOPEN':([2,4,5,12,13,18,19,20,22,23,28,],[-2,-1,-19,17,-17,-3,-18,-16,-6,-4,-5,]),'TRANSITION':([1,17,],[6,6,]),'TAGCLOSE':([6,7,8,9,10,11,15,16,24,25,29,32,33,],[-11,-10,-9,-7,-19,-8,-13,23,28,-19,-12,-14,-15,]),'ATTRVALOPEN':([21,],[26,]),'BUTTON':([1,17,],[7,7,]),'OBJECT':([1,17,],[8,8,]),'SCENE':([1,17,],[9,9,]),'MANIFEST':([1,17,],[11,11,]),'ATTRVALSTR':([26,],[30,]),'ATTRVALCLOSE1':([31,],[33,]),'TAGLONE':([6,7,8,9,10,11,15,16,25,29,32,33,],[-11,-10,-9,-7,-19,-8,-13,22,-19,-12,-14,-15,]),'ATTRVALSTR1':([27,],[31,]),'ATTRS':([6,7,8,9,10,11,25,32,33,],[-11,-10,-9,-7,14,-8,14,-14,-15,]),'ATTRVALCLOSE':([30,],[32,]),'ATTRVALOPEN1':([21,],[27,]),'ATTRASSIGN':([14,],[21,]),'TAGOPEN':([0,2,4,5,12,13,18,19,20,22,23,28,],[1,-2,-1,-19,1,-17,-3,-18,-16,-6,-4,-5,]),'$end':([2,3,4,18,22,28,],[-2,0,-1,-3,-6,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'atributo':([21,],[25,]),'closetag':([12,],[18,]),'lonetag':([0,12,],[2,2,]),'tag':([0,12,],[3,19,]),'attrs':([10,25,],[16,29,]),'tagname':([1,17,],[10,24,]),'child':([5,],[12,]),'simpletag':([0,12,],[4,4,]),'opentag':([0,12,],[5,5,]),'children':([12,],[20,]),'lambda':([5,10,25,],[13,15,15,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> tag","S'",1,None,None,None),
  ('tag -> simpletag','tag',1,'p_tag','jera.py',120),
  ('tag -> lonetag','tag',1,'p_tag','jera.py',121),
  ('simpletag -> opentag child closetag','simpletag',3,'p_simpletag','jera.py',126),
  ('opentag -> TAGOPEN tagname attrs TAGCLOSE','opentag',4,'p_opentag','jera.py',135),
  ('closetag -> TAGCLOSEOPEN tagname TAGCLOSE','closetag',3,'p_closetag','jera.py',151),
  ('lonetag -> TAGOPEN tagname attrs TAGLONE','lonetag',4,'p_lonetag','jera.py',155),
  ('tagname -> SCENE','tagname',1,'p_tagname','jera.py',172),
  ('tagname -> MANIFEST','tagname',1,'p_tagname','jera.py',173),
  ('tagname -> OBJECT','tagname',1,'p_tagname','jera.py',174),
  ('tagname -> BUTTON','tagname',1,'p_tagname','jera.py',175),
  ('tagname -> TRANSITION','tagname',1,'p_tagname','jera.py',176),
  ('attrs -> ATTRS ATTRASSIGN atributo attrs','attrs',4,'p_attrs','jera.py',181),
  ('attrs -> lambda','attrs',1,'p_attrs','jera.py',182),
  ('atributo -> ATTRVALOPEN ATTRVALSTR ATTRVALCLOSE','atributo',3,'p_atributo','jera.py',193),
  ('atributo -> ATTRVALOPEN1 ATTRVALSTR1 ATTRVALCLOSE1','atributo',3,'p_atributo','jera.py',194),
  ('child -> child children','child',2,'p_child','jera.py',200),
  ('child -> lambda','child',1,'p_child','jera.py',201),
  ('children -> tag','children',1,'p_children','jera.py',213),
  ('lambda -> <empty>','lambda',0,'p_lambda','jera.py',217),
]
